package GeneracioCodiIntermedi;
public enum OperacionsCTA {
    // OPERACIONS ARITÈTIQUES I LÒGIQUES
    COPIA, SUMA, RESTA, PRODUCTE, DIVISIO, MODUL, MENYS, AND, OR, NOT,
    // OPERACIONS INDEXACIÓ
    INDVAL, INDASS,
    // OPERACIONS DE BIFURCACIÓ
    SKIP, GOTO, IF, LT, LE, EQ, NE, GE, GT,
    // CRIDES A PROCEDIMENTS
    PMB, CALL, RTN, PARAMS, PARAMC;
}